/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as common from "./common";
export * as extensions from "./extensions";
export { SCPolygon2__factory } from "./SCPolygon2__factory";
