/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as extensions from "./extensions";
export type { extensions };
export type { SCPolygon2 } from "./SCPolygon2";
