/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as scPolygon1 from "./sc-polygon-1";
export * as scPolygon2 from "./sc-polygon-2";
export * as scPolygon3 from "./sc-polygon-3";
