/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SCTradeContract } from "./SCTradeContract";
export type { SimpleERC721 } from "./SimpleERC721";
