/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scPolygon1 from "./sc-polygon-1";
export type { scPolygon1 };
import type * as scPolygon2 from "./sc-polygon-2";
export type { scPolygon2 };
import type * as scPolygon3 from "./sc-polygon-3";
export type { scPolygon3 };
